package com.budget.buddy.presentation.ui.categories

val listScrol = listOf(
    CategoriesItemData(
        CategoryIcons.FOOD.title,
        CategoryIcons.FOOD.icons
    ),
    CategoriesItemData(
        CategoryIcons.RESTAURANT.title,
        CategoryIcons.RESTAURANT.icons
    ),
    CategoriesItemData(
        CategoryIcons.MEDICINE.title,
        CategoryIcons.MEDICINE.icons
    ),
    CategoriesItemData(
        CategoryIcons.ENTERTAINMENT.title,
        CategoryIcons.ENTERTAINMENT.icons
    ),
    CategoriesItemData(
        CategoryIcons.BEAUTY.title,
        CategoryIcons.BEAUTY.icons
    ),
    CategoriesItemData(
        CategoryIcons.HOME.title,
        CategoryIcons.HOME.icons
    ),
    CategoriesItemData(
        CategoryIcons.PETS.title,
        CategoryIcons.PETS.icons
    ),
    CategoriesItemData(
        CategoryIcons.CLOTHES.title,
        CategoryIcons.CLOTHES.icons
    ),
    CategoriesItemData(
        CategoryIcons.SPORT.title,
        CategoryIcons.SPORT.icons
    ),
    CategoriesItemData(
        CategoryIcons.TRANSPORT.title,
        CategoryIcons.TRANSPORT.icons
    ),
    CategoriesItemData(
        CategoryIcons.TAXI.title,
        CategoryIcons.TAXI.icons
    ),
    CategoriesItemData(
        CategoryIcons.TRAVEL.title,
        CategoryIcons.TRAVEL.icons
    ),
    CategoriesItemData(
        CategoryIcons.OTHER.title,
        CategoryIcons.OTHER.icons
    ),
)